# Generated by Django 3.2.14 on 2022-07-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220707_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cation',
            new_name='caption',
        ),
    ]
